### ISSUE TITLE
[how-to-use-ollama-sidecar-open-webui-frontend-cloud-run-gpu]:

### ISSUE THREAD

**Issue by wugwei** [googlecodelabs/feedback#1462]
Step 7.
service.yaml

Incorrect：
`image: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/ollama-sidecar-codelab/openwebui`
Correct：
`image: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/ollama-sidecar-codelab-repo/openwebui`

Incorrect：
`image: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/ollama-sidecar-codelab/ollama-gemma-2b`
Correct：
`image: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/ollama-sidecar-codelab-repo/ollama-gemma-2b`

#This memory value will cause "Out-of-memory event detected in container", Try 2Gi is good. 
```
       - name: WEBUI_AUTH
          value: 'false'
        resources:
          limits:
            memory: 1Gi
            cpu: 2000m
        volumeMounts:
        - name: in-memory-1
          mountPath: /app/backend/data
```

Deploy to Cloud Run, open the Service URL: HTTP 403
Need to refer to the following URL allow unauthenticated invocations
https://cloud.google.com/run/docs/authenticating/public?hl=zh-cn#yaml
