### ISSUE TITLE
[cloud-mongodb-statefulset]:

### ISSUE THREAD

**Issue by JuddRogers** [googlecodelabs/feedback#501]
This stanza is out of date:
```
volumeClaimTemplates:
 - metadata:
     name: mongo-persistent-storage
     annotations:
       volume.beta.kubernetes.io/storage-class: "fast"
```
need to update the annotations:
```
 volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        StorageClassName: "fast"
```
I actually used "standard" storage class when trying it out.
