### ISSUE TITLE
[cloud-mongodb-statefulset]:

### ISSUE THREAD

**Issue by gangalearning** [googlecodelabs/feedback#517]
as per the instructions, after execing into one of the mongo pods and execting rs.config() gives the below error, instead of listing all the replicas. Hence unable to proceed with the next steps.

> rs.config()
2018-11-24T11:50:19.345+0000 E QUERY    [js] Error: Could not retrieve replica set config: {
        "operationTime" : Timestamp(0, 0),
        "ok" : 0,
        "errmsg" : "no replset config has been received",
        "code" : 94,
        "codeName" : "NotYetInitialized",
        "$clusterTime" : {
                "clusterTime" : Timestamp(0, 0),
                "signature" : {
                        "hash" : BinData(0,"AAAAAAAAAAAAAAAAAAAAAAAAAAA="),
                        "keyId" : NumberLong(0)
                }
        }
} :
rs.conf@src/mongo/shell/utils.js:1448:11
@(shell):1:1

**Comment by eickeBuecking** [comment]
You have to ensure that mongo listens for connections:
```

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  ---
  template:
    ---
    spec:
      ---
      containers:
         - ---
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip" 
            - 0.0.0.0     
            - "--smallfiles"
            - "--noprealloc"
     ---
```
