### ISSUE TITLE
[cloud-running-a-container]: No resources found in default namespace

### ISSUE THREAD

**Issue by sainisumit1** [googlecodelabs/feedback#763]
On this page https://codelabs.developers.google.com/codelabs/cloud-running-a-nodejs-container/index.html?index=..%2F..index#4

```
cloudshell:~/codelabs/nodejs-docs-samples/containerengine/hello-world (my-user-project-276021)$ kubectl get pods
NAME         READY   STATUS    RESTARTS   AGE
hello-node   1/1     Running   0          22m

cloudshell:~/codelabs/nodejs-docs-samples/containerengine/hello-world (my-user-project-276021)$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                                       READY   STATUS    RESTARTS   AGE
default       hello-node                                                 1/1     Running   0          15m
kube-system   event-exporter-v0.2.5-599d65f456-4dnqw                     2/2     Running   0          29m

cloudshell:~/codelabs/nodejs-docs-samples/containerengine/hello-world (my-user-project-276021)$ kubectl get deployments
No resources found in default namespace.

cloudshell:~/codelabs/nodejs-docs-samples/containerengine/hello-world (my-user-project-276021)$ kubectl get deployments --all-namespaces
NAMESPACE     NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   event-exporter-v0.2.5                      1/1     1            1           29m
kube-system   fluentd-gcp-scaler                         1/1     1            1           29m
kube-system   heapster-gke                               1/1     1            1           29m
kube-system   kube-dns                                   2/2     2            2           29m
kube-system   kube-dns-autoscaler                        1/1     1            1           29m
kube-system   l7-default-backend                         1/1     1            1           29m
kube-system   metrics-server-v0.3.1                      1/1     1            1           29m
kube-system   stackdriver-metadata-agent-cluster-level   1/1     1            1           29m
```

I tried googling to find the reason why default namespace is missing in "deployments" but in vain. 
Is this related to security authZ?
Please suggest the solution and help me to understand the reason.

**Comment by sainisumit1** [comment]
Training doc seems to be prepared on an old version of kubectl and not updated since then.
kubectl 1.18 is not creating the deployments with pods so we have to create it using yaml.

Create a new yaml like following:

```
vi deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
  namespace: default
  labels:
    app: hello-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node-container
        image: gcr.io/<actual project ID>/hello-node:1.0
        ports:
        - containerPort: 8080
```
and execute the following command:
```
kubectl apply -f deployment.yml
```
