### ISSUE TITLE
[cloud-mongodb-statefulset]:

### ISSUE THREAD

**Issue by walkerrandolphsmith** [googlecodelabs/feedback#804]
This was relevant to me and the suggestion worked: 
https://support.squidex.io/t/mongodb-connection-failed-to-connect-to-database-squidex/1775/10

mongo container shows:
```
> rs.status()
{
        "info" : "run rs.initiate(...) if not yet done for the set",
        "ok" : 0,
        "errmsg" : "no replset config has been received",
        "code" : 94,
        "codeName" : "NotYetInitialized"
}
```

mongo-sidecar shows:
```
‘pods is forbidden: User “system:serviceaccount:default:default” cannot list resource “pods” in API group “” at the cluster scope’,
```

Solution:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: default-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
```
